# workflow 名稱
name: RunFTToolsLauncher

# 什麼情況下觸發 workflow
on:
  # 對於 main branch 建立 Branch 與 Pull Request 時觸發 workflow 
  # push:
  #  branches: [ main ]
  # pull_request:
  #  branches: [ main ]

  # 允許你從 Action 頁簽上手動執行 workflow
  workflow_dispatch:

# Job 可以循序或平行執行
jobs:
  # 這個 workflow 只有一個 job，名稱為 "build"
  build:
    # 這個 job 會執行在作業系統為 ubuntu 的 runner
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    # 作為 Job 的一部分，Steps 會循序執行一連串的動作
    steps:
      - name: 透過 FTToolLauncher 執行 ALM TestSet
        # run: cd c:\FTToolsLauncher;.\FTToolsLauncher_net48.exe -paramfile RunALM.properties
        run: cd c:\FTToolsLauncher;.\FTToolsLauncher.exe -paramfile RunALM.properties

      # - name: 執行 FTToolsLauncher
      #  run: .\FTToolsLauncher_net48.exe -paramfile RunALM.properties
        
